from fpdf import FPDF
from io import BytesIO

class ModernInvoice(FPDF):
    def header(self):
        # Light grey header bar
        self.set_fill_color(245, 245, 245)
        self.rect(0, 0, 210, 25, 'F')

        # Business name
        self.set_font("Arial", "B", 20)
        self.set_text_color(40, 40, 40)
        self.set_xy(10, 8)
        self.cell(0, 10, self.business_name, ln=True)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by LAC Accounting Automations", 0, 0, "C")


def generate_pdf(data, mode="invoice", output_path=None):
    pdf = ModernInvoice()
    pdf.business_name = data.get("business_name", "Invoice")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # -------------------------
    # CLIENT DETAILS SECTION
    # -------------------------
    pdf.set_font("Arial", "", 12)
    pdf.set_text_color(80, 80, 80)
    pdf.ln(10)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Invoice Details", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Client: {data.get('client_name', 'Demo Client')}", ln=True)
    pdf.cell(0, 8, f"Reference No: {data.get('reference', 'INV-001')}", ln=True)

    pdf.ln(5)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # -------------------------
    # TABLE HEADER (Modern)
    # -------------------------
    pdf.set_font("Arial", "B", 11)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_text_color(60, 60, 60)

    pdf.cell(80, 10, "Description", border=0, fill=True)
    pdf.cell(20, 10, "Qty", border=0, fill=True)
    pdf.cell(40, 10, "Unit Price", border=0, fill=True)
    pdf.cell(40, 10, "Total", border=0, fill=True, ln=True)

    # Divider line
    pdf.set_draw_color(230, 230, 230)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # -------------------------
    # TABLE CONTENT
    # -------------------------
    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(50, 50, 50)

    subtotal = 0
    items = data.get("items", [])

    if not items:
        pdf.cell(0, 8, "No items available.", ln=True)
    else:
        for item in items:
            desc = str(item.get("description", "")).strip()
            qty = float(item.get("quantity", 1))
            unit_price = float(item.get("unit_price", 0))
            total = float(item.get("total", qty * unit_price))
            subtotal += total

            pdf.cell(80, 8, desc, border=0)
            pdf.cell(20, 8, str(qty), border=0)
            pdf.cell(40, 8, f"R{unit_price:,.2f}", border=0)
            pdf.cell(40, 8, f"R{total:,.2f}", border=0, ln=True)

    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # -------------------------
    # TOTALS SECTION (AIRBNB STYLE)
    # -------------------------
    vat = subtotal * 0.15
    total_due = subtotal + vat

    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(80, 80, 80)

    pdf.cell(0, 8, f"Subtotal: R{subtotal:,.2f}", ln=True)
    pdf.cell(0, 8, f"VAT (15%): R{vat:,.2f}", ln=True)

    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, f"Total Due: R{total_due:,.2f}", ln=True)

    # -------------------------
    # THANK YOU
    # -------------------------
    pdf.ln(10)
    pdf.set_font("Arial", "I", 11)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 10, "Thank you for your business!", ln=True)

    # -------------------------
    # OUTPUT
    # -------------------------
    if output_path:
        pdf.output(output_path)
        return None

    buffer = BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
